packages:
  - apps/*
  - packages/frp
  - packages/wechat
  - packages/network

onlyBuiltDependencies:
  - '@alicloud/openapi-core'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - msw
  - sharp
inject-workspace-packages: true
