packages:
  - apps/admin
  - apps/front
  - config
  - packages/frp
  - packages/wechat
  - packages/react
  - packages/network
  - packages/adonis

onlyBuiltDependencies:
  - '@alicloud/openapi-core'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - msw
  - sharp
