/* tslint:disable */
/* eslint-disable */
/**
 * web
 * API documentation generated from start/routes.ts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Captcha200Response
 */
export interface Captcha200Response {
    /**
     * 
     * @type {object}
     * @memberof Captcha200Response
     */
    'key'?: object;
    /**
     * 
     * @type {object}
     * @memberof Captcha200Response
     */
    'svg'?: object;
}

