/* tslint:disable */
/* eslint-disable */
/**
 * web
 * API documentation generated from start/routes.ts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CoreUploadPost200ResponseProperties } from './core-upload-post200-response-properties';

/**
 * 
 * @export
 * @interface CoreUploadPost200Response
 */
export interface CoreUploadPost200Response {
    /**
     * 
     * @type {object}
     * @memberof CoreUploadPost200Response
     */
    'type'?: object;
    /**
     * 
     * @type {CoreUploadPost200ResponseProperties}
     * @memberof CoreUploadPost200Response
     */
    'properties'?: CoreUploadPost200ResponseProperties;
}

