/* tslint:disable */
/* eslint-disable */
/**
 * web
 * API documentation generated from start/routes.ts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InitiatePayment200ResponseData } from './initiate-payment200-response-data';

/**
 * 
 * @export
 * @interface InitiatePayment200Response
 */
export interface InitiatePayment200Response {
    /**
     * 
     * @type {object}
     * @memberof InitiatePayment200Response
     */
    'code'?: object;
    /**
     * 
     * @type {object}
     * @memberof InitiatePayment200Response
     */
    'message'?: object;
    /**
     * 
     * @type {InitiatePayment200ResponseData}
     * @memberof InitiatePayment200Response
     */
    'data'?: InitiatePayment200ResponseData;
}

