/* tslint:disable */
/* eslint-disable */
/**
 * web
 * API documentation generated from start/routes.ts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    'perPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    'lastPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    'firstPage'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginationMeta
     */
    'lastPageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginationMeta
     */
    'firstPageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginationMeta
     */
    'nextPageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginationMeta
     */
    'previousPageUrl'?: string;
}

