/* tslint:disable */
/* eslint-disable */
/**
 * web
 * API documentation generated from start/routes.ts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * User (Model)
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'nickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'mobile'?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'sex'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'real_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'avatar'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'home'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'weibo'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'wechat'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'github'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'qq'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'openid'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'unionid'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'is_lock'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'updated_at'?: string;
}

