/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  FindPasswords: () => import('#controllers/find_passwords_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
