/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CacheSchema extends BaseModel {
  static $columns = ['expiresAt', 'key', 'value'] as const
  $columns = CacheSchema.$columns
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare key: string
  @column()
  declare value: string | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'id', 'orderableId', 'orderableType', 'payState', 'payType', 'price', 'sn', 'subject', 'tradeNo', 'updatedAt', 'userId'] as const
  $columns = OrderSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare data: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderableId: bigint | number
  @column()
  declare orderableType: string
  @column()
  declare payState: boolean
  @column()
  declare payType: string | null
  @column()
  declare price: string
  @column()
  declare sn: string
  @column()
  declare subject: string
  @column()
  declare tradeNo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['key', 'points', 'expire'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare key: string
  @column()
  declare points: number
  @column()
  declare expire: bigint | number | null
}

export class UploadSchema extends BaseModel {
  static $columns = ['id', 'userId', 'url', 'name', 'extension', 'size', 'driver', 'mime', 'createdAt', 'updatedAt'] as const
  $columns = UploadSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare url: string
  @column()
  declare name: string
  @column()
  declare extension: string
  @column()
  declare size: number
  @column()
  declare driver: string
  @column()
  declare mime: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['address', 'avatar', 'createdAt', 'email', 'github', 'home', 'id', 'isLock', 'mobile', 'name', 'nickname', 'openid', 'password', 'qq', 'realName', 'sex', 'unionid', 'updatedAt', 'wechat', 'weibo'] as const
  $columns = UserSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare github: string | null
  @column()
  declare home: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isLock: boolean
  @column()
  declare mobile: string | null
  @column()
  declare name: string | null
  @column()
  declare nickname: string | null
  @column()
  declare openid: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare qq: string | null
  @column()
  declare realName: string | null
  @column()
  declare sex: boolean
  @column()
  declare unionid: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wechat: string | null
  @column()
  declare weibo: string | null
}
