/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteRouteImport } from './routes/member/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as FrontRouteRouteImport } from './routes/_front/route'
import { Route as FrontIndexRouteImport } from './routes/_front/index'
import { Route as MemberProfileRouteImport } from './routes/member/profile'
import { Route as MemberBindRouteImport } from './routes/member/bind'
import { Route as AuthWechatRouteImport } from './routes/auth/wechat'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgetRouteImport } from './routes/auth/forget'
import { Route as FrontLessonRouteImport } from './routes/_front/lesson'
import { Route as FrontARouteImport } from './routes/_front/a'

const MemberRouteRoute = MemberRouteRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontRouteRoute = FrontRouteRouteImport.update({
  id: '/_front',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontIndexRoute = FrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontRouteRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberBindRoute = MemberBindRouteImport.update({
  id: '/bind',
  path: '/bind',
  getParentRoute: () => MemberRouteRoute,
} as any)
const AuthWechatRoute = AuthWechatRouteImport.update({
  id: '/wechat',
  path: '/wechat',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgetRoute = AuthForgetRouteImport.update({
  id: '/forget',
  path: '/forget',
  getParentRoute: () => AuthRouteRoute,
} as any)
const FrontLessonRoute = FrontLessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => FrontRouteRoute,
} as any)
const FrontARoute = FrontARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => FrontRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FrontIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/a': typeof FrontARoute
  '/lesson': typeof FrontLessonRoute
  '/auth/forget': typeof AuthForgetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/wechat': typeof AuthWechatRoute
  '/member/bind': typeof MemberBindRoute
  '/member/profile': typeof MemberProfileRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/a': typeof FrontARoute
  '/lesson': typeof FrontLessonRoute
  '/auth/forget': typeof AuthForgetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/wechat': typeof AuthWechatRoute
  '/member/bind': typeof MemberBindRoute
  '/member/profile': typeof MemberProfileRoute
  '/': typeof FrontIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_front': typeof FrontRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/_front/a': typeof FrontARoute
  '/_front/lesson': typeof FrontLessonRoute
  '/auth/forget': typeof AuthForgetRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/wechat': typeof AuthWechatRoute
  '/member/bind': typeof MemberBindRoute
  '/member/profile': typeof MemberProfileRoute
  '/_front/': typeof FrontIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/member'
    | '/a'
    | '/lesson'
    | '/auth/forget'
    | '/auth/login'
    | '/auth/register'
    | '/auth/wechat'
    | '/member/bind'
    | '/member/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/member'
    | '/a'
    | '/lesson'
    | '/auth/forget'
    | '/auth/login'
    | '/auth/register'
    | '/auth/wechat'
    | '/member/bind'
    | '/member/profile'
    | '/'
  id:
    | '__root__'
    | '/_front'
    | '/auth'
    | '/member'
    | '/_front/a'
    | '/_front/lesson'
    | '/auth/forget'
    | '/auth/login'
    | '/auth/register'
    | '/auth/wechat'
    | '/member/bind'
    | '/member/profile'
    | '/_front/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FrontRouteRoute: typeof FrontRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MemberRouteRoute: typeof MemberRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_front': {
      id: '/_front'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_front/': {
      id: '/_front/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FrontIndexRouteImport
      parentRoute: typeof FrontRouteRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/bind': {
      id: '/member/bind'
      path: '/bind'
      fullPath: '/member/bind'
      preLoaderRoute: typeof MemberBindRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/auth/wechat': {
      id: '/auth/wechat'
      path: '/wechat'
      fullPath: '/auth/wechat'
      preLoaderRoute: typeof AuthWechatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forget': {
      id: '/auth/forget'
      path: '/forget'
      fullPath: '/auth/forget'
      preLoaderRoute: typeof AuthForgetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_front/lesson': {
      id: '/_front/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof FrontLessonRouteImport
      parentRoute: typeof FrontRouteRoute
    }
    '/_front/a': {
      id: '/_front/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof FrontARouteImport
      parentRoute: typeof FrontRouteRoute
    }
  }
}

interface FrontRouteRouteChildren {
  FrontARoute: typeof FrontARoute
  FrontLessonRoute: typeof FrontLessonRoute
  FrontIndexRoute: typeof FrontIndexRoute
}

const FrontRouteRouteChildren: FrontRouteRouteChildren = {
  FrontARoute: FrontARoute,
  FrontLessonRoute: FrontLessonRoute,
  FrontIndexRoute: FrontIndexRoute,
}

const FrontRouteRouteWithChildren = FrontRouteRoute._addFileChildren(
  FrontRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgetRoute: typeof AuthForgetRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthWechatRoute: typeof AuthWechatRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgetRoute: AuthForgetRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthWechatRoute: AuthWechatRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MemberRouteRouteChildren {
  MemberBindRoute: typeof MemberBindRoute
  MemberProfileRoute: typeof MemberProfileRoute
}

const MemberRouteRouteChildren: MemberRouteRouteChildren = {
  MemberBindRoute: MemberBindRoute,
  MemberProfileRoute: MemberProfileRoute,
}

const MemberRouteRouteWithChildren = MemberRouteRoute._addFileChildren(
  MemberRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FrontRouteRoute: FrontRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MemberRouteRoute: MemberRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
