/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FrontRouteRouteImport } from './routes/_front/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as FrontIndexRouteImport } from './routes/_front/index'
import { Route as FrontLessonRouteImport } from './routes/_front/lesson'
import { Route as AuthWechatRouteImport } from './routes/_auth/wechat'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgetRouteImport } from './routes/_auth/forget'

const FrontRouteRoute = FrontRouteRouteImport.update({
  id: '/_front',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontIndexRoute = FrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontRouteRoute,
} as any)
const FrontLessonRoute = FrontLessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => FrontRouteRoute,
} as any)
const AuthWechatRoute = AuthWechatRouteImport.update({
  id: '/wechat',
  path: '/wechat',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgetRoute = AuthForgetRouteImport.update({
  id: '/forget',
  path: '/forget',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FrontIndexRoute
  '/forget': typeof AuthForgetRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/wechat': typeof AuthWechatRoute
  '/lesson': typeof FrontLessonRoute
}
export interface FileRoutesByTo {
  '/': typeof FrontIndexRoute
  '/forget': typeof AuthForgetRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/wechat': typeof AuthWechatRoute
  '/lesson': typeof FrontLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_front': typeof FrontRouteRouteWithChildren
  '/_auth/forget': typeof AuthForgetRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/wechat': typeof AuthWechatRoute
  '/_front/lesson': typeof FrontLessonRoute
  '/_front/': typeof FrontIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forget' | '/login' | '/register' | '/wechat' | '/lesson'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forget' | '/login' | '/register' | '/wechat' | '/lesson'
  id:
    | '__root__'
    | '/_auth'
    | '/_front'
    | '/_auth/forget'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/wechat'
    | '/_front/lesson'
    | '/_front/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  FrontRouteRoute: typeof FrontRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_front': {
      id: '/_front'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_front/': {
      id: '/_front/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FrontIndexRouteImport
      parentRoute: typeof FrontRouteRoute
    }
    '/_front/lesson': {
      id: '/_front/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof FrontLessonRouteImport
      parentRoute: typeof FrontRouteRoute
    }
    '/_auth/wechat': {
      id: '/_auth/wechat'
      path: '/wechat'
      fullPath: '/wechat'
      preLoaderRoute: typeof AuthWechatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forget': {
      id: '/_auth/forget'
      path: '/forget'
      fullPath: '/forget'
      preLoaderRoute: typeof AuthForgetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgetRoute: typeof AuthForgetRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthWechatRoute: typeof AuthWechatRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgetRoute: AuthForgetRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthWechatRoute: AuthWechatRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface FrontRouteRouteChildren {
  FrontLessonRoute: typeof FrontLessonRoute
  FrontIndexRoute: typeof FrontIndexRoute
}

const FrontRouteRouteChildren: FrontRouteRouteChildren = {
  FrontLessonRoute: FrontLessonRoute,
  FrontIndexRoute: FrontIndexRoute,
}

const FrontRouteRouteWithChildren = FrontRouteRoute._addFileChildren(
  FrontRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  FrontRouteRoute: FrontRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
