/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemberRouteRouteImport } from './routes/member/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as FrontRouteRouteImport } from './routes/_front/route'
import { Route as FrontIndexRouteImport } from './routes/_front/index'
import { Route as MemberProfileRouteImport } from './routes/member/profile'
import { Route as MemberBindRouteImport } from './routes/member/bind'
import { Route as AuthWechatLoginRouteImport } from './routes/auth/wechatLogin'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthFindPasswordRouteImport } from './routes/auth/findPassword'
import { Route as FrontPackageRouteImport } from './routes/_front/package'

const MemberRouteRoute = MemberRouteRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontRouteRoute = FrontRouteRouteImport.update({
  id: '/_front',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontIndexRoute = FrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontRouteRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRouteRoute,
} as any)
const MemberBindRoute = MemberBindRouteImport.update({
  id: '/bind',
  path: '/bind',
  getParentRoute: () => MemberRouteRoute,
} as any)
const AuthWechatLoginRoute = AuthWechatLoginRouteImport.update({
  id: '/wechatLogin',
  path: '/wechatLogin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthFindPasswordRoute = AuthFindPasswordRouteImport.update({
  id: '/findPassword',
  path: '/findPassword',
  getParentRoute: () => AuthRouteRoute,
} as any)
const FrontPackageRoute = FrontPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => FrontRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FrontIndexRoute
  '/admin': typeof AdminRouteRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/package': typeof FrontPackageRoute
  '/auth/findPassword': typeof AuthFindPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/wechatLogin': typeof AuthWechatLoginRoute
  '/member/bind': typeof MemberBindRoute
  '/member/profile': typeof MemberProfileRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/package': typeof FrontPackageRoute
  '/auth/findPassword': typeof AuthFindPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/wechatLogin': typeof AuthWechatLoginRoute
  '/member/bind': typeof MemberBindRoute
  '/member/profile': typeof MemberProfileRoute
  '/': typeof FrontIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_front': typeof FrontRouteRouteWithChildren
  '/admin': typeof AdminRouteRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/_front/package': typeof FrontPackageRoute
  '/auth/findPassword': typeof AuthFindPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/wechatLogin': typeof AuthWechatLoginRoute
  '/member/bind': typeof MemberBindRoute
  '/member/profile': typeof MemberProfileRoute
  '/_front/': typeof FrontIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/member'
    | '/package'
    | '/auth/findPassword'
    | '/auth/login'
    | '/auth/register'
    | '/auth/wechatLogin'
    | '/member/bind'
    | '/member/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/member'
    | '/package'
    | '/auth/findPassword'
    | '/auth/login'
    | '/auth/register'
    | '/auth/wechatLogin'
    | '/member/bind'
    | '/member/profile'
    | '/'
  id:
    | '__root__'
    | '/_front'
    | '/admin'
    | '/auth'
    | '/member'
    | '/_front/package'
    | '/auth/findPassword'
    | '/auth/login'
    | '/auth/register'
    | '/auth/wechatLogin'
    | '/member/bind'
    | '/member/profile'
    | '/_front/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FrontRouteRoute: typeof FrontRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MemberRouteRoute: typeof MemberRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_front': {
      id: '/_front'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_front/': {
      id: '/_front/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FrontIndexRouteImport
      parentRoute: typeof FrontRouteRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/member/bind': {
      id: '/member/bind'
      path: '/bind'
      fullPath: '/member/bind'
      preLoaderRoute: typeof MemberBindRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/auth/wechatLogin': {
      id: '/auth/wechatLogin'
      path: '/wechatLogin'
      fullPath: '/auth/wechatLogin'
      preLoaderRoute: typeof AuthWechatLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/findPassword': {
      id: '/auth/findPassword'
      path: '/findPassword'
      fullPath: '/auth/findPassword'
      preLoaderRoute: typeof AuthFindPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_front/package': {
      id: '/_front/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof FrontPackageRouteImport
      parentRoute: typeof FrontRouteRoute
    }
  }
}

interface FrontRouteRouteChildren {
  FrontPackageRoute: typeof FrontPackageRoute
  FrontIndexRoute: typeof FrontIndexRoute
}

const FrontRouteRouteChildren: FrontRouteRouteChildren = {
  FrontPackageRoute: FrontPackageRoute,
  FrontIndexRoute: FrontIndexRoute,
}

const FrontRouteRouteWithChildren = FrontRouteRoute._addFileChildren(
  FrontRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthFindPasswordRoute: typeof AuthFindPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthWechatLoginRoute: typeof AuthWechatLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthFindPasswordRoute: AuthFindPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthWechatLoginRoute: AuthWechatLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MemberRouteRouteChildren {
  MemberBindRoute: typeof MemberBindRoute
  MemberProfileRoute: typeof MemberProfileRoute
}

const MemberRouteRouteChildren: MemberRouteRouteChildren = {
  MemberBindRoute: MemberBindRoute,
  MemberProfileRoute: MemberProfileRoute,
}

const MemberRouteRouteWithChildren = MemberRouteRoute._addFileChildren(
  MemberRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FrontRouteRoute: FrontRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MemberRouteRoute: MemberRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
